In [1]:
import numpy as np

In [2]:
n1 = np.array([[34,65,7],[12,49,85]])
n1

array([[34, 65,  7],
       [12, 49, 85]])

In [3]:
n2 = np.array([[70,11,24],[2,66,40]])
n2

array([[70, 11, 24],
       [ 2, 66, 40]])

In [4]:
x = np.array([n1,n2])

In [5]:
x

array([[[34, 65,  7],
        [12, 49, 85]],

       [[70, 11, 24],
        [ 2, 66, 40]]])

In [6]:
x.shape

(2, 2, 3)

In [7]:
x_manual = np.array([[[34,65,7],[12,49,85],[70,11,24],[2,66,40]]])

In [8]:
x_manual

array([[[34, 65,  7],
        [12, 49, 85],
        [70, 11, 24],
        [ 2, 66, 40]]])

In [14]:
c1 = np.array([[4,65,74,2],[11,40,90,60]])
c1

array([[ 4, 65, 74,  2],
       [11, 40, 90, 60]])

In [17]:
c2 = np.array([[1,5,7,9],[88,24,5,10]])
c2

array([[ 1,  5,  7,  9],
       [88, 24,  5, 10]])

In [18]:
x =np.array([c1,c2])

In [19]:
x

array([[[ 4, 65, 74,  2],
        [11, 40, 90, 60]],

       [[ 1,  5,  7,  9],
        [88, 24,  5, 10]]])

In [20]:
x.shape

(2, 2, 4)

In [21]:
x_manual = np.array([[[ 4, 65, 74,  2],[11, 40, 90, 60],[ 1,  5,  7,  9],[88, 24,  5, 10]]])

In [22]:
x_manual

array([[[ 4, 65, 74,  2],
        [11, 40, 90, 60],
        [ 1,  5,  7,  9],
        [88, 24,  5, 10]]])