In [1]:
!pip install tensorflow

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [2]:
import tensorflow as tf
print(tf.__version__)

2.8.2


In [3]:
scalar = tf.constant(12)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=12>

In [4]:
scalar.ndim

0

In [5]:
vector = tf.constant([12,67])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([12, 67], dtype=int32)>

In [6]:
vector.ndim

1

In [7]:
matrix = tf.constant([[1,5],
                     [56,80]])

In [8]:
matrix.ndim

2

In [10]:
next_matrix = tf.constant([[4.,9.],
                           [76.,1.],
                           [9.,41.]], dtype=tf.float16)
next_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[ 4.,  9.],
       [76.,  1.],
       [ 9., 41.]], dtype=float16)>

In [11]:
next_matrix.ndim

2

In [14]:
tensor = tf.constant([[[4,9,8],
                           [76,2,11]],
                          [[90,41,5],
                           [1,7,34]],
                          [[57,48,25],
                           [10,27,60]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 4,  9,  8],
        [76,  2, 11]],

       [[90, 41,  5],
        [ 1,  7, 34]],

       [[57, 48, 25],
        [10, 27, 60]]], dtype=int32)>

In [15]:
tensor.ndim

3

In [17]:
changeable_tensor = tf.Variable([12,5])
unchangeable_tensor = tf.constant([12,5])
changeable_tensor, unchangeable_tensor 

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([12,  5], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([12,  5], dtype=int32)>)

In [19]:
changeable_tensor[0].assign(5)
changeable_tensor 

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([5, 5], dtype=int32)>

In [20]:
unchangeable_tensor[0].assign(5)
unchangeable_tensor 

AttributeError: ignored

Creating random tensors

In [23]:
random_1 = tf.random.Generator.from_seed(8)
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(8)
random_2 = random_2.normal(shape=(3,2))

random_1, random_2, random_1 == random_2 

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.69211644,  0.84215707],
        [-0.06378496,  0.92800784],
        [-0.6039789 , -0.1766927 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.69211644,  0.84215707],
        [-0.06378496,  0.92800784],
        [-0.6039789 , -0.1766927 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [27]:
not_shuffled = tf.constant([[2,7],
                           [8,25],
                           [35,79]])

tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  7],
       [35, 79],
       [ 8, 25]], dtype=int32)>

In [30]:
tf.random.shuffle(not_shuffled, seed =8)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [31]:
tf.random.set_seed = 8

tf.random.shuffle(not_shuffled, seed=8)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

Other ways to make tensors

In [32]:
tf.ones(shape=(4,2))

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

In [33]:
tf.zeros(shape=(4,2))

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

You can also turn NumPy arrays in into tensors

In [37]:
import numpy as np
numpy_A = np.arange(1,40, dtype=np.int32)
A = tf.constant(numpy_A,
                shape=[1,3,13])
numpy_A, A

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
        35, 36, 37, 38, 39], dtype=int32),
 <tf.Tensor: shape=(1, 3, 13), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13],
         [14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26],
         [27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39]]],
       dtype=int32)>)

In [39]:
import numpy as np
numpy_A = np.arange(1,65, dtype=np.int32)
A = tf.constant(numpy_A,
                shape=[2,8,4])

numpy_A, A

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
        35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
        52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64], dtype=int32),
 <tf.Tensor: shape=(2, 8, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12],
         [13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24],
         [25, 26, 27, 28],
         [29, 30, 31, 32]],
 
        [[33, 34, 35, 36],
         [37, 38, 39, 40],
         [41, 42, 43, 44],
         [45, 46, 47, 48],
         [49, 50, 51, 52],
         [53, 54, 55, 56],
         [57, 58, 59, 60],
         [61, 62, 63, 64]]], dtype=int32)>)

Getting information from tensors (shape, rank, size)

In [40]:
rank_4_tensor = tf.zeros([2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor = tf.zeros([2, 3, 4, 5])
rank_4_tensor

In [41]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

 Get various attributes of tensor

In [42]:
print("datatype of every elemet:", rank_4_tensor.dtype)
print("number of dimensions (rank):", rank_4_tensor.ndim)
print("shape of tensor:", rank_4_tensor.shape)
print("elements along axis 0 of tensor:", rank_4_tensor.shape[0])
print("elements along last axis of tensor:", rank_4_tensor.shape[-1])
print("total number of elements (2*3*4*5):", tf.size(rank_4_tensor).numpy())

datatype of every elemet: <dtype: 'float32'>
number of dimensions (rank): 4
shape of tensor: (2, 3, 4, 5)
elements along axis 0 of tensor: 2
elements along last axis of tensor: 5
total number of elements (2*3*4*5): 120


Get the first 2 items of each dimension

In [43]:
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

Get the dimension from each index except for the final one

In [44]:
rank_4_tensor[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

# Create a rank 2 tensor (2 dimensions)

In [49]:
rank_2_tensor = tf.constant([[6,9],
                             [26,75]])

Get the last item of each row

In [50]:
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 9, 75], dtype=int32)>

Add an extra dimension (to the end)

In [51]:
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_2_tensor, rank_3_tensor

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 6,  9],
        [26, 75]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
 array([[[ 6],
         [ 9]],
 
        [[26],
         [75]]], dtype=int32)>)

In [53]:
tf.expand_dims(rank_2_tensor, axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[ 6],
        [ 9]],

       [[26],
        [75]]], dtype=int32)>

Manipulating tensors (tensor operations)

In [65]:
tensor = tf.constant([[65,28],[90,41]])
tensor + 28

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 93,  56],
       [118,  69]], dtype=int32)>

In [66]:
tensor * 9

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[585, 252],
       [810, 369]], dtype=int32)>

In [67]:
tensor - 50

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 15, -22],
       [ 40,  -9]], dtype=int32)>

In [68]:
tf.multiply(tensor, 4)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[260, 112],
       [360, 164]], dtype=int32)>

Matrix multiplication in TensorFlow

In [69]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[65, 28],
       [90, 41]], dtype=int32)>

In [70]:
print(tensor)
tf.matmul(tensor, tensor)

tf.Tensor(
[[65 28]
 [90 41]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[6745, 2968],
       [9540, 4201]], dtype=int32)>

In [71]:
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[6745, 2968],
       [9540, 4201]], dtype=int32)>

In [72]:
X= tf.constant([[4,9],
               [57,8],
               [12,7]])

Y= tf.constant([[90,80],
                [11,54],
                [2,49]])

In [73]:
tf.reshape(Y, shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[90, 80, 11],
       [54,  2, 49]], dtype=int32)>

In [74]:
X @ tf.reshape(Y, shape=(2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 846,  338,  485],
       [5562, 4576, 1019],
       [1458,  974,  475]], dtype=int32)>

In [75]:
tf.transpose(X)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 4, 57, 12],
       [ 9,  8,  7]], dtype=int32)>

In [76]:
tf.matmul(tf.transpose(X), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1011, 3986],
       [ 912, 1495]], dtype=int32)>

In [77]:
tf.matmul(a=X, b=Y, transpose_a=True, transpose_b=False)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1011, 3986],
       [ 912, 1495]], dtype=int32)>

In [79]:
tf.tensordot(tf.transpose(X), Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1011, 3986],
       [ 912, 1495]], dtype=int32)>

In [80]:
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1080,  530,  449],
       [5770, 1059,  506],
       [1640,  510,  367]], dtype=int32)>

In [82]:
tf.matmul(X, tf.reshape(Y, (2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 846,  338,  485],
       [5562, 4576, 1019],
       [1458,  974,  475]], dtype=int32)>

Check shapes of Y, reshaped Y and tranposed Y

In [83]:
Y.shape, tf.reshape(Y, (2,3)).shape, tf.transpose(Y).shape

(TensorShape([3, 2]), TensorShape([2, 3]), TensorShape([2, 3]))

In [85]:
print("Normal Y:")
print(Y, "\n")

print("Y reshaped to (2,3):")
print(tf.reshape(Y, (2,3)), "\n")

print("Y transposed:")
print(tf.transpose(Y))

Normal Y:
tf.Tensor(
[[90 80]
 [11 54]
 [ 2 49]], shape=(3, 2), dtype=int32) 

Y reshaped to (2,3):
tf.Tensor(
[[90 80 11]
 [54  2 49]], shape=(2, 3), dtype=int32) 

Y transposed:
tf.Tensor(
[[90 11  2]
 [80 54 49]], shape=(2, 3), dtype=int32)


Changing the datatype of a tensor

In [86]:
B = tf.constant([2.8, 90.47])
C = tf.constant([3,90])
B, C

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 2.8 , 90.47], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 3, 90], dtype=int32)>)

In [ ]:
B = tf.constant([1.7, 7.4])

# Create a new tensor with default datatype (int32)
C = tf.constant([1, 7])
B, C

In [87]:
B = tf.cast(B, dtype=tf.float16)
B

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([ 2.8, 90.5], dtype=float16)>

In [88]:
C = tf.cast(C, dtype=tf.float32)
C

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 3., 90.], dtype=float32)>

In [89]:
D = tf.constant([-90,-27])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([-90, -27], dtype=int32)>

In [90]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([90, 27], dtype=int32)>

In [91]:
E = tf.constant(np.random.randint(low =0, high = 100, size = 50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([89, 19, 73, 74, 90,  9, 93, 14, 96, 43, 60, 14, 22, 99, 88, 71, 40,
       16,  8, 63, 84, 81, 24, 85, 35, 21, 39,  4, 15, 99, 62, 52, 61, 64,
       18, 27, 96,  6, 38, 12, 22, 98, 14, 66,  8, 86, 39, 76, 76, 39])>

In [92]:
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=4>

In [93]:
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [94]:
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2528>

In [98]:
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=50>

In [99]:
F =  tf.constant(np.random.random(50))
F

<tf.Tensor: shape=(50,), dtype=float64, numpy=
array([6.60453471e-01, 9.12879488e-01, 6.38690116e-01, 6.76241952e-01,
       5.58583013e-01, 6.50082962e-01, 5.55095996e-01, 6.06567789e-01,
       5.10430641e-02, 1.33862248e-01, 3.52695433e-01, 9.74348775e-01,
       7.75551628e-04, 7.56547537e-02, 1.52889409e-01, 4.00740199e-01,
       2.93151600e-01, 9.44456768e-01, 5.00766495e-01, 5.61892083e-01,
       8.49547756e-01, 6.80348279e-01, 6.97514887e-01, 2.04888323e-01,
       5.67995219e-01, 6.95751889e-02, 9.04993225e-01, 4.98486136e-01,
       7.39925270e-02, 2.10826981e-01, 3.91460141e-01, 6.14365990e-01,
       9.48092974e-01, 8.33156774e-01, 2.93512432e-01, 1.54666920e-01,
       6.58791225e-01, 4.88045779e-02, 5.90253915e-01, 9.78143625e-01,
       7.88204154e-01, 4.57410406e-02, 4.55232508e-01, 6.48837438e-01,
       1.82401287e-01, 1.46215155e-01, 4.71969369e-01, 5.50068447e-01,
       2.83821728e-01, 7.15199148e-01])>

In [101]:
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=39>

In [102]:
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=12>

In [106]:
print(f"the maximum value of F is at position: {tf.argmax(F).numpy()}")
print(f"the maximum value of F is: {tf.reduce_max(F).numpy()}")
print(f"using tf.argmax() to index F, the maximum value of F is: {F[tf.argmax(F)].numpy()}")
print(f"are the two amx values the same (they should be)? {F[tf.argmax(F)].numpy() == tf.reduce_max(F).numpy()}")

the maximum value of F is at position: 39
the maximum value of F is: 0.9781436245011322
using tf.argmax() to index F, the maximum value of F is: 0.9781436245011322
are the two amx values the same (they should be)? True


Squeezing a tensor (removing all single dimensions

In [109]:
G = tf.constant(np.random.randint(0, 100, 50), shape=(1,1,1,1,50))
G.shape, G.ndim

(TensorShape([1, 1, 1, 1, 50]), 5)

In [110]:
G_squeezed = tf.squeeze(G)
G_squeezed.shape, G_squeezed.ndim

(TensorShape([50]), 1)

One-hot encoding

In [114]:
a_list = [0,1,2,3]

tf.one_hot(a_list, depth =4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [115]:
tf.one_hot(a_list, depth=4, on_value="money girl!", off_value="browny girls!")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'money girl!', b'browny girls!', b'browny girls!',
        b'browny girls!'],
       [b'browny girls!', b'money girl!', b'browny girls!',
        b'browny girls!'],
       [b'browny girls!', b'browny girls!', b'money girl!',
        b'browny girls!'],
       [b'browny girls!', b'browny girls!', b'browny girls!',
        b'money girl!']], dtype=object)>

Squaring, log, square root


In [116]:
H  =tf.constant(np.arange(1,10))
H

<tf.Tensor: shape=(9,), dtype=int64, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [117]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int64, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])>

In [119]:
tf.sqrt(H)

InvalidArgumentError: ignored

In [120]:
H =tf.cast(H, dtype=tf.float32)
H

<tf.Tensor: shape=(9,), dtype=float32, numpy=array([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)>

In [121]:
tf.sqrt(H)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.99999994, 1.4142134 , 1.7320508 , 1.9999999 , 2.236068  ,
       2.4494896 , 2.6457512 , 2.8284268 , 3.        ], dtype=float32)>

In [123]:
tf.math.log(H)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

In [125]:
I = tf.Variable(np.arange(0,5))
I

<tf.Variable 'Variable:0' shape=(5,) dtype=int64, numpy=array([0, 1, 2, 3, 4])>

In [128]:
I.assign([0,1,2,3,50])

<tf.Variable 'UnreadVariable' shape=(5,) dtype=int64, numpy=array([ 0,  1,  2,  3, 50])>

In [129]:
I

<tf.Variable 'Variable:0' shape=(5,) dtype=int64, numpy=array([ 0,  1,  2,  3, 50])>

In [130]:
I.assign_add([12,12,12,12,12])

<tf.Variable 'UnreadVariable' shape=(5,) dtype=int64, numpy=array([12, 13, 14, 15, 62])>

In [131]:
I

<tf.Variable 'Variable:0' shape=(5,) dtype=int64, numpy=array([12, 13, 14, 15, 62])>

Tensors and NumPy

In [133]:
J= tf.constant(np.array([4., 8., 14.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 4.,  8., 14.])>

In [135]:
np.array(J), type(np.array(J))

(array([ 4.,  8., 14.]), numpy.ndarray)

In [136]:
J.numpy(), type(J.numpy())

(array([ 4.,  8., 14.]), numpy.ndarray)

Create a tensor from NumPy and from an array

In [137]:
numpy_J = tf.constant(np.array([4.,8.,14.]))
tensor_j = tf.constant([4.,8.,14.])
numpy_J.dtype, tensor_j.dtype

(tf.float64, tf.float32)

Using @tf.function

In [138]:
def function(x, y):
  return x ** 2 + y

x = tf.constant(np.arange(0,10))
y = tf.constant(np.arange(10,20))
function(x, y)

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([ 10,  12,  16,  22,  30,  40,  52,  66,  82, 100])>

In [141]:
@tf.function
def tf_function(x, y):
  return x ** 2 + y

tf_function(x, y)

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([ 10,  12,  16,  22,  30,  40,  52,  66,  82, 100])>

Finding access to GPUs

In [142]:
print(tf.config.list_physical_devices('GPU'))

[]


In [143]:
import tensorflow as tf
print(tf.config.list_physical_devices('GPU'))

[]


In [144]:
!nvidia-smi

NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.

